# Site settings
title: Neapolitan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Three girls, a guy, and a pizza place
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: founderscoders
# github_username:  neapolitan-a-la-code

# Build settings
markdown: kramdown
