# Site settings
title: Neapolitan-à-la-code
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  More than just coding.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://neapolitans.com" # the base hostname & protocol for your site
instagram_username: a.la.code
twitter_username: founderscoders
github_username:  Neapolitan-a-la-Code

# Build settings
markdown: kramdown
